fastlane_version "1.46.1"

platform :ios do
                
        lane :beta do
            increment_build_number(
              xcodeproj: './ios/goodidea.xcodeproj'
            )

            sh("xctool -project ../ios/goodidea.xcodeproj -scheme goodidea clean archive -archivePath ../build/goodidea")

            sh("xcodebuild -exportArchive -exportFormat ipa -archivePath ../build/goodidea.xcarchive -exportPath ../build/goodidea.ipa -exportProvisioningProfile 'iOS Team Provisioning Profile: *'")        

            sh("cp ../build/goodidea.ipa $BITRISE_DEPLOY_DIR")
        end

end